version: "3"
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "my-secret-pw"
    ports: 
      - 3307:3306


  
  adminer:
    image: adminer
    restart: always
    ports:
        - 8081:8080
