"""added

Revision ID: 587c2ae43e58
Revises: 
Create Date: 2024-08-23 22:58:47.051880

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '587c2ae43e58'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=40),
               existing_nullable=False)
        batch_op.alter_column('released',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=40),
               existing_nullable=False)
        batch_op.alter_column('director',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=40),
               existing_nullable=False)
        batch_op.alter_column('genre',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=40),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie', schema=None) as batch_op:
        batch_op.alter_column('genre',
               existing_type=sa.String(length=40),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('director',
               existing_type=sa.String(length=40),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('released',
               existing_type=sa.String(length=40),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=40),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
